# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        banner:
            quality: 80
            filters:
                upscale:
                    min: [900, 600]
                thumbnail:
                    size: [900, 600]
                    mode: outbound
        square:
            quality: 80
            filters:
                thumbnail:
                    size: [100, 150]
                    mode: outbound

        logoLogin:
            quality: 80
            filters:
                thumbnail:
                    size: [35, 35]
                    mode: outbound
